### ISSUE TITLE
Regarding ios app crash

### ISSUE THREAD

**Issue by PratikHyperlink** [TapResearch/TapResearch-iOS-SDK#1]
Hello ,

When user is doing the survey and when he taps on "abandon" button then the app gets crashed.
Please fix the issue as early as possible.

**Comment by drnkenmonkey** [comment]
Thanks for bringing this issue to our attention. 

We were able to reproduce this crash when we double tap the "abandon" button. Is this consistent with what you are seeing?

**Comment by PratikHyperlink** [comment]
Hello,
i integrated the new sdk(v.1.2.1) and i dint faced the abandon issue anymore after testing several times.
Thank you for fixing.
