### ISSUE TITLE
Crash at ver 2.3.1 - 2.5.3 [TRNetworkManager directGetOffers:success:failure:]

### ISSUE THREAD

**Issue by susslik** [TapResearch/TapResearch-iOS-SDK#22]
Hello,

After updating the SDK to 2.3.1 we are seeing crashes inside TapResearchSDK at Crashlytics. Affected iOS versions at the moment are: iOS 14.8.0, iOS 15.0.0, iOS 15.0.1, iOS 15.1.0. Assume those crashes can have the same reason. 

**Stack Traces from Crashlytics**:

1) EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000b3785d400
0  libobjc.A.dylib                0x25dd0 objc_release + 16
1  TapResearchSDK                 0xc9ec -[TRNetworkManager directGetOffers:success:failure:] + 424
2  TapResearchSDK                 0x326ac -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x32540 -[TRPlacementPollingThread main] + 48
4  Foundation                     0x17a30c __NSThread__start__ + 864
5  libsystem_pthread.dylib        0x1bfc _pthread_start + 320
6  libsystem_pthread.dylib        0xa758 thread_start + 8

2) EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000a0aea2d176f0
0  libobjc.A.dylib                0x15e0 objc_msgSend + 32
1  TapResearchSDK                 0xc9a0 -[TRNetworkManager directGetOffers:success:failure:] + 348
2  TapResearchSDK                 0x326ac -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x32540 -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6836c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
6  libsystem_pthread.dylib        0xea0 thread_start + 8

3) EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000005410368a0
0  libobjc.A.dylib                0x2840 objc_retain + 16
1  TapResearchSDK                 0xca24 -[TRNetworkManager directGetOffers:success:failure:] + 480
2  TapResearchSDK                 0x326ac -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x32540 -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6464c __NSThread__start__ + 776
5  libsystem_pthread.dylib        0x2458 _pthread_start + 116
6  libsystem_pthread.dylib        0xab0 thread_start + 8

4) EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000006be3f1ec0
0  libobjc.A.dylib                0x3490 objc_retain + 16
1  TapResearchSDK                 0xc990 -[TRNetworkManager directGetOffers:success:failure:] + 332
2  TapResearchSDK                 0x326ac -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x32540 -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6895c __NSThread__start__ + 792
5  libsystem_pthread.dylib        0x1a60 _pthread_start + 148
6  libsystem_pthread.dylib        0xf5c thread_start + 8

**Comment by susslik** [comment]
Hey Tap Research team!
Recently we upgraded to Tap Research SDK ver 2.4.1 but those crashes still appears (about 150 crashes per week). The stack traces looks a little bit different (the numbers of the lines were changed):

**A)** EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000058436d220
0  libobjc.A.dylib                0x3110 objc_release + 16
1  TapResearchSDK                 0xa730 -[TRNetworkManager directGetOffers:success:failure:] + 624
2  TapResearchSDK                 0x17ae4 -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x1797c -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6855c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

**B)** EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000047fc228a0
0  libobjc.A.dylib                0x3110 objc_release + 16
1  TapResearchSDK                 0xa6a4 -[TRNetworkManager directGetOffers:success:failure:] + 484
2  TapResearchSDK                 0x17ae4 -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x1797c -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6855c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

**C)** EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000820385040
0  libobjc.A.dylib                0x3970 objc_retain + 16
1  TapResearchSDK                 0xa6dc -[TRNetworkManager directGetOffers:success:failure:] + 540
2  TapResearchSDK                 0x17ae4 -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x1797c -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6855c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19ac _pthread_start + 148
6  libsystem_pthread.dylib        0xe68 thread_start + 8

**D)** EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000d38f24560
0  libobjc.A.dylib                0x3490 objc_retain + 16
1  TapResearchSDK                 0xa648 -[TRNetworkManager directGetOffers:success:failure:] + 392
2  TapResearchSDK                 0x17ae4 -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x1797c -[TRPlacementPollingThread main] + 48
4  Foundation                     0x6836c __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
6  libsystem_pthread.dylib        0xea0 thread_start + 8

**E)** EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x000000109133c210
0  libobjc.A.dylib                0x62ec lookUpImpOrForward + 96
1  libobjc.A.dylib                0x19e4 _objc_msgSend_uncached + 68
2  TapResearchSDK                 0xa658 -[TRNetworkManager directGetOffers:success:failure:] + 408
3  TapResearchSDK                 0x17ae4 -[TRPlacementPollingThread getOffers] + 188
4  TapResearchSDK                 0x1797c -[TRPlacementPollingThread main] + 48
5  Foundation                     0x683fc __NSThread__start__ + 808
6  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
7  libsystem_pthread.dylib        0xea0 thread_start + 8

**F)** EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00001717ea5c5090
0  libobjc.A.dylib                0x1540 objc_msgSend + 32
1  TapResearchSDK                 0xa6ec -[TRNetworkManager directGetOffers:success:failure:] + 556
2  TapResearchSDK                 0x17ae4 -[TRPlacementPollingThread getOffers] + 188
3  TapResearchSDK                 0x1797c -[TRPlacementPollingThread main] + 48
4  Foundation                     0x683fc __NSThread__start__ + 808
5  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
6  libsystem_pthread.dylib        0xea0 thread_start + 8

But assume these is the same crashes we had at 2.3.1 (please, check my first message at this issue for the details).

**Comment by susslik** [comment]
Hi @jeroen-tap! 
Some time ago we release a new app version with TapResearch SDK ver. 2.4.2 - unfortunately those crashes are still not fixed -(
Could you please take a look?

**Comment by philip-tap** [comment]
> Hi @jeroen-tap! Some time ago we release a new app version with TapResearch SDK ver. 2.4.2 - unfortunately those crashes are still not fixed -( Could you please take a look?

Hi @susslik, 

We deployed a backend fix for this issue previously, but it appears the SDK will also need a minor update. We will test around directGetOffers and review a resolution for the next iteration. Thanks for sending over your crash information. Will follow up when we have a timeline for next release.

**Comment by susslik** [comment]
Hi @philip-tap, 
Any updates on this? Recently we released the app with TapResearch SDK ver. 2.5.3 - and the crashes are still here. 
That's the top crashes on our app at the moment

**Comment by psymike** [comment]
Hi @susslik - We released version 2.5.5 that solves this issue.
Please reopen if you continue to see these crashes. Thanks!
