### ISSUE TITLE
Xcode 13.1 Failed to build module 'TapResearchSDK' v.2.4.0

### ISSUE THREAD

**Issue by susslik** [TapResearch/TapResearch-iOS-SDK#26]
Hello! After updated TapResearchSDK Xcode build fails with the following error:

Failed to build module 'TapResearchSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', while this compiler is 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)'). Please select a toolchain which matches the SDK.

Could you check that, please?

**Comment by abcreationIT** [comment]
I have the same problem too.

Please update the SDK.

**Comment by taylortap** [comment]
We are aware of the conflict occurring with Swift 5.5 and Xcode 13.1 - our next release (mid Jan) will up the Swift version to mitigate the issue.

**Comment by abcreationIT** [comment]
@taylortap OK thanks.
We look forward to the next release.

**Comment by abcreationIT** [comment]
@taylortap @susslik now works with SDK 2.4.1

Thank you

**Comment by taylortap** [comment]
we are now considering this issue closed
