### ISSUE TITLE
TapResearch.setNavigationBarColor not work

### ISSUE THREAD

**Issue by abcreationIT** [TapResearch/TapResearch-iOS-SDK#28]
Hello, I've updated to the new SDK 2.4.1 but I noticed a graphic error if you set the navigation bar colors.

Swift code:
`TapResearch.setNavigationBarColor(.yellow)`  
`TapResearch.setNavigationBarTextColor(.black)`

Result:
![Simulator Screen Shot - iPhone 13 Pro - 2022-01-16 at 17 13 06](https://user-images.githubusercontent.com/33608547/149668221-4470da3c-af9b-4793-a3a8-f16f12541836.png)

As you can see the yellow color of the navigation bar is not set correctly.

**Technical data:**
Xcode versione: 13.2.1
Simulator version: iOS 15.2
SDK version: 2.4.1

**Comment by jeroen-tap** [comment]
We can confirm this issue and will include a fix in our next SDK release

**Comment by taylortap** [comment]
We're aware of this issue, as it's related to a UIKit change in iOS 15. A fix is ready and slated for our next release.

**Comment by abcreationIT** [comment]
@jeroen-tap when is the SDK update that fixes this bug expected to be released?
Just to know, I need to do an App Store update of my app and I would like to understand whether to wait.

Thanks

**Comment by jeroen-tap** [comment]
@abcreationIT  We are anticipating a release late February or March to address other issues and we have included this resolution. In the meantime you might be able to use something like:
`UINavigationBar.appearance().backgroundColor = UIColor.red`
`UINavigationBar.appearance().titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.white]`
before showing our placement to set the navigation bar colors and resetting when leaving (when the previous view controller will appear).

**Comment by jeroen-tap** [comment]
Hi @abcreationIT we've just updated the SDK to v2.4.2 which should help with the nav bar styling issue.
