### ISSUE TITLE
How to re-initialize a TRPlacement if the functions is deprecated?

### ISSUE THREAD

**Issue by abcreationIT** [TapResearch/TapResearch-iOS-SDK#29]
[TapResearch iOS SDK integration guide](https://supply-docs.tapresearch.com/docs/ios-integration/#placements) says:

> A placement can only show the survey wall once. After the survey wall is dismissed, you'll have to initialize a new **TRPlacement** object if you want the user to go back to TapResearch.

So my question is (after a test in my iOS app): 
How can I re-initialize a **TRPlacement** if from version 2.3.0 the SDK initializes the **TRPlacements** automatically?
(the function `TapResearch.initPlacement(withIdentifier:)` is deprecated...)

[TapResearch iOS SDK integration guide](https://supply-docs.tapresearch.com/docs/ios-integration/#placements) says:
> The SDK now initializes placements for you internally.

**Comment by taylortap** [comment]
The SDK now initializes placements automatically, with no need to initialize manually. Thanks for bringing to our attention verbiage that needs to be changed in the integration guide.

**Comment by abcreationIT** [comment]
@taylortap I don't understand how to show the SurveyWall again if the placement is no longer available.

Actual documentation says:
> A placement can only show the survey wall once. After the survey wall is dismissed, you'll have to initialize a new TRPlacement object if you want the user to go back to TapResearch.

In fact currently after calling `placement.showSurveyWall(with: ...)`, survey wall is no longer available and so I don't know how to reload it to show it again.

**Comment by Sanjay-Codeb** [comment]
@abcreationIT How did you handled this. Have you figured out any way to fix this?
