### ISSUE TITLE
Add SPM support

### ISSUE THREAD

**Issue by susslik** [TapResearch/TapResearch-iOS-SDK#38]
Hi TapResearch team!
Recently we faced some troubles with CocoaPods so decided to migrate to SPM. But unfortunately, TapReasearch does not offer installation via SPM. 
Probably would be possible to add SPM option to TapReasearch SDK?

Best,
Sergey

**Comment by philip-tap** [comment]
Hi @susslik,

Wanted to let you know this is an item on our list and we are looking into it shortly. Will reply as soon as I have an update or timeline here.
