### ISSUE TITLE
Crash on double click on 'Complete' or 'Survey wall' on TapResearch '2.0.11'

### ISSUE THREAD

**Issue by dchirita** [TapResearch/TapResearch-iOS-SDK#5]
Hello,

The following crash happens when you double click on 'Complete' or 'Survey wall'.

Call stack:

* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 23.1
    frame #0: 0x0000000105c3ba95 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x0000000110f6afac CoreFoundation`_CFThrowFormattedException + 194
    frame #2: 0x000000011108bbb6 CoreFoundation`-[__NSDictionaryM setObject:forKey:] + 1046
    frame #3: 0x000000010328c0f5 Stipped`-[TRSurveyURLRequest initWithSurveyURL:andCPIdentifier:errorMessage:errorCode:](self=0x0000600001ba4ba0, _cmd="initWithSurveyURL:andCPIdentifier:errorMessage:errorCode:", surveyURLString=@"https://www.tapresearch.com/router/offers/22f64bb94a67a73c2461fce08296b098/pre_entry?sdk=true&uid=017483e0-a604-11e3-a975-237cbee23ed9&did=2A6E2B13-7072-4367-9890-BE943971E971&offer_reason=0&timestamp=1596183143&asid=1&version=2.0.11&pass_through_values=eyJyZXF1ZXN0SWQiOiJhNGEwOGYxMi1jYjNhLTM3YTgtODBkZC1jOTNlNWM0Zjg2YTAifQ==", cpIdentifier=0x0000000000000000, errMessage=@"The operation couldn’t be completed. (NSURLErrorDomain error -999.)", errCode=-999) at TRSurveyURLRequest.m:50:9
  * frame #4: 0x00000001032643c6 Stipped`-[TRWebviewController webView:didFailProvisionalNavigation:withError:](self=0x00007fad41cd1a10, _cmd="webView:didFailProvisionalNavigation:withError:", webView=0x00007fad42270000, navigation=0x00007fad41cdfd50, error=domain: @"NSURLErrorDomain" - code: 18446744073709550617) at TRWebviewController.m:339:35
    frame #5: 0x000000010cc5cb26 WebKit`WebKit::NavigationState::NavigationClient::didFailProvisionalNavigationWithError(WebKit::WebPageProxy&, WebKit::WebFrameProxy&, API::Navigation*, WebCore::ResourceError const&, API::Object*) + 154
    frame #6: 0x000000010ccbd84c WebKit`WebKit::WebPageProxy::didFailProvisionalLoadForFrameShared(WTF::Ref<WebKit::WebProcessProxy, WTF::DumbPtrTraits<WebKit::WebProcessProxy> >&&, unsigned long long, WebCore::SecurityOriginData const&, unsigned long long, WTF::String const&, WebCore::ResourceError const&, WebKit::UserData const&) + 1002
    frame #7: 0x000000010ccbd43a WebKit`WebKit::WebPageProxy::didFailProvisionalLoadForFrame(unsigned long long, WebCore::SecurityOriginData const&, unsigned long long, WTF::String const&, WebCore::ResourceError const&, WebKit::UserData const&) + 76
    frame #8: 0x000000010cec6334 WebKit`void IPC::handleMessage<Messages::WebPageProxy::DidFailProvisionalLoadForFrame, WebKit::WebPageProxy, void (WebKit::WebPageProxy::*)(unsigned long long, WebCore::SecurityOriginData const&, unsigned long long, WTF::String const&, WebCore::ResourceError const&, WebKit::UserData const&)>(IPC::Decoder&, WebKit::WebPageProxy*, void (WebKit::WebPageProxy::*)(unsigned long long, WebCore::SecurityOriginData const&, unsigned long long, WTF::String const&, WebCore::ResourceError const&, WebKit::UserData const&)) + 190
    frame #9: 0x000000010cb27b46 WebKit`IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 126
    frame #10: 0x000000010cce0e84 WebKit`WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 24
    frame #11: 0x000000010cb1aa18 WebKit`IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 108
    frame #12: 0x000000010cb1d42d WebKit`IPC::Connection::dispatchIncomingMessages() + 717
    frame #13: 0x0000000109d5b2e4 JavaScriptCore`WTF::RunLoop::performWork() + 228
    frame #14: 0x0000000109d5b572 JavaScriptCore`WTF::RunLoop::performWork(void*) + 34
    frame #15: 0x0000000110f83db1 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #16: 0x0000000110f83633 CoreFoundation`__CFRunLoopDoSources0 + 243
    frame #17: 0x0000000110f7dcef CoreFoundation`__CFRunLoopRun + 1231
    frame #18: 0x0000000110f7d4d2 CoreFoundation`CFRunLoopRunSpecific + 626
    frame #19: 0x00000001137b72fe GraphicsServices`GSEventRunModal + 65
    frame #20: 0x000000011931afc2 UIKitCore`UIApplicationMain + 140
    ------------------------------Stripped----------------------------------
    frame #22: 0x00000001125fb541 libdyld.dylib`start + 1
    frame #23: 0x00000001125fb541 libdyld.dylib`start + 1

**Comment by psymike** [comment]
Closing due to age.
