### ISSUE TITLE
TapResearch 3.1.0-beta2 don't work with XCode 15.0

### ISSUE THREAD

**Issue by susslik** [TapResearch/TapResearch-iOS-SDK#54]
Getting an error when trying to build/run the project:
Compiled module was created by a different version of the compiler '5.8.0.124.5'; rebuild 'TapResearchSDK' and try again.

**Comment by susslik** [comment]
Hi @jeroen-tap, @icaspi, @gmccullough - any updates on this?

**Comment by jeroen-tap** [comment]
@susslik Thanks for letting us know, we’re on it and will release a compatible build very soon!
