### ISSUE TITLE
Duplicate symbols in projects that already integrate  AFNetworking

### ISSUE THREAD

**Issue by dchirita** [TapResearch/TapResearch-iOS-SDK#6]
Steps to reproduce:

1.  New Swift project
2. Create Podfile like:

**#use_frameworks!**
 pod 'TapResearch', '2.0.11'
 pod 'AFNetworking', '3.2.1'

Notice that **#use_frameworks!** is commented - so not using use_frameworks!

3. Pod install
4. Create bridging header in order to import: #import <TapResearchSDK/TapResearchSDK.h>
5. Run/Compile

Expected:
There should be no warnings

Actual: 

ld: warning: meta method 'af_safeImageWithData:' in category from /Users/...CurrentUserHere..../Library/Developer/Xcode/DerivedData/....ProductNameHere..../Build/Products/Debug-iphonesimulator/AFNetworking/libAFNetworking.a(AFURLResponseSerialization.o) conflicts with same method from another category

**Comment by psymike** [comment]
Closing due to age
